### ISSUE TITLE
Cannot edit Issue

### ISSUE THREAD

**Issue by radike** [radike/issue-tracker#8]
Similar to #7

**Comment by tomillie** [comment]
Fixed. The problem was in missing ReporterId and Created fields in edit form. I've corrected it by inserting hidden fields into the form. Better solution would be to use ViewModel.

**Comment by radike** [comment]
The fix allows to change Reporter and Created, which should not be possible.

**Comment by tomillie** [comment]
Yes, that's why I've mentioned that using ViewModel is better solution. We will probably need another viewModel to implement comment section anyway.. Another possible fix is to clear errors in ModelState. Before checking that ModelState is valid, there should be something like this:
_ModelState["ReportedId"].Errors.Clear();_

**Comment by tomillie** [comment]
I've added viewModel and it should be ok now.
